export const SET_TOKEN_FROM_STORAGE = "SET_TOKEN_FROM_STORAGE";

export const FETCH_USER_BEGIN = "FETCH_USER_BEGIN";
export const FETCH_USER_SUCCESS = "FETCH_USER_SUCCESS";
export const FETCH_USER_FAIL = "FETCH_USER_FAIL";
export const FETCH_USER_FINAL = "FETCH_USER_FINAL";

export const CHECK_AUTHORIZATION_SUCCESS = "CHECK_AUTHORIZATION_SUCCESS";
export const CHECK_AUTHORIZATION_FAIL = "CHECK_AUTHORIZATION_FAIL";
export const CHECK_AUTHORIZATION_FINAL = "CHECK_AUTHORIZATION_FINAL";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";

export const GET_PERMISSIONS_SUCCESS = "GET_PERMISSIONS_SUCCESS";
